Controllers/AdminUserController.cs
using DataEntry_Tracker.DAL;
using DataEntry_Tracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataEntry_Tracker.Controllers
{
    public class AdminUserController : Controller
    {
        AdminUserDAL adminUserDal = new AdminUserDAL();
        TrackerDAL trackerDal = new TrackerDAL();

        public ActionResult AdminUserView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            return View();
        }
        [HttpPost]
        public ActionResult AllMasterRequest()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            return PartialView("_allRequestPartialView", adminUserDal.AllMasterRequest(userid));
        }

        public ActionResult GetRequestAdmin(int RequestId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            CommonModel returnmodel = trackerDal.GetRequestInformationByReId(RequestId);
            returnmodel.RevisionList = new List<CommonModel>();
            returnmodel.RevisionList = trackerDal.GetMerchandRivisionProgress(RequestId);
            return PartialView("_AdminShowAllTaskByRequest", returnmodel);
        }
        public ActionResult DataEntryAssignProgress()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            return Json(adminUserDal.CoordinatorDashboard(userID), JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetCoordinatorFilesDatabase(int RequestId, int Reqcod, int OperationId, int Revision, string Partial)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            CommonModel comolList = trackerDal.DetailsInformationRequest(RequestId, OperationId, Revision, userid, Reqcod);
            return PartialView(Partial, comolList);
        }
        public ActionResult GetAdminPending(int Status)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            List<CommonModel> commonlist = adminUserDal.GetAdminPending(userID, Status);
            return PartialView("_adminTaskPartial", commonlist);
        }
        [HttpPost]
        public ActionResult GetDataEntryReport(string FormDate,string ToDate)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            List<ReportModel> Reportlist = adminUserDal.GetDataEntryReport(FormDate, ToDate);
            return PartialView("_reportdataTableadmin", Reportlist);
        }
    }
}

Controllers/TrackerController.cs
using DataEntry_Tracker.DAL;
using DataEntry_Tracker.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataEntry_Tracker.Controllers
{
    public class TrackerController : Controller
    {

        TrackerDAL trackerDAL = new TrackerDAL();
        // GET: Tracker
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetUnitsFromDataBase()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetUnitsDatabase(userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetBuyerFromDataBase()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetBuyerFromDatabase(userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult LoadPoCatagory()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<LoadPoCatagory> comolList = trackerDAL.LoadPoFromDataBase(userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetAllBaseOperationsDatabase()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> baselist = trackerDAL.GetAllBasOperation(userid);
            return Json(baselist, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetSeasonFromDatabase(int buyerId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetSeasonFromDatabas(buyerId, userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetStylesFromFromDatabase(int seasonId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetStylesFromDatabase(seasonId,userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetFilesFromDatabase(int RequestId,int Status)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<FileUploadModel> comolList = trackerDAL.GetFilesByRivisionRequest(RequestId,Status);
            return PartialView("_showAllNewUploadFiles", comolList);
        }

        public ActionResult GetCoordinatorFilesDatabase(int RequestId, int Reqcod, int OperationId,int Revision,string Partial)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            CommonModel comolList = trackerDAL.DetailsInformationRequest(RequestId,OperationId,Revision,userid,Reqcod);
            return PartialView(Partial, comolList);
        }

        public ActionResult CoordinatorDetailsFirstime(int RequestId, int Reqcod, int OperationId, int Revision, string Partial,int Status)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            if (Status == 0)
            {
                bool res = trackerDAL.CordinatorTimeUpdate(Reqcod);
            }
            CommonModel comolList = trackerDAL.DetailsInformationRequest(RequestId, OperationId, Revision, userid, Reqcod);
            return PartialView(Partial, comolList);
        }

        public ActionResult CreateSupplyChain(int RequestId, int NumberTrans,string Partial)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);

            CommonModel comolList = new CommonModel();
            comolList.RequestCodId = RequestId;
            comolList.NoOfTransections = NumberTrans;
            return PartialView(Partial, comolList);
        }


        public ActionResult CreateMarchandiseRequest()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }
        public ActionResult MerchandiseCreateView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }
        public ActionResult DataEntryView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }

        public ActionResult CoordinatorView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }
        [HttpPost]
        public ActionResult AllRequestById()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            return PartialView("_allRequestPartialView",trackerDAL.GetAllRequestById(userid));
        }

        [HttpPost]
        public ActionResult DeleteFiles(int FileuploadId,int TableName)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            string filepath = trackerDAL.DeleteFile(FileuploadId,userID,TableName);
            bool result = false;
                    try
                    {
                        System.IO.File.Delete(filepath);
                        result = true;
                    }
                    catch (IOException ioExp)
                    {
                        Console.WriteLine(ioExp.Message);
                        result = false;
                    }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GenarateNewRequest(CommonModel commonModel)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            CommonModel returnmodel = trackerDAL.SaveRequestReturnPrimarykey(commonModel,userID);
            returnmodel.BuyerName = Server.HtmlDecode(commonModel.BuyerName);
            return PartialView("_merchandiseOperationCreation", returnmodel);
        }

        [HttpPost]
        public ActionResult GetRequestInformationById(int RequestId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            CommonModel returnmodel = trackerDAL.GetRequestInformationByReId(RequestId);
            returnmodel.RevisionList = new List<CommonModel>();
            returnmodel.RevisionList = trackerDAL.GetMerchandRivisionProgress(RequestId);
            return PartialView("_merchandiseOperationCreation", returnmodel);
        }

        public ActionResult GetPendingRequest(int Pending,int DataOrCo)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> commonModels = new List<CommonModel>();
            commonModels = trackerDAL.GetAllPendingRequest(Pending,userid,DataOrCo);
            if (DataOrCo == 1)
            {
                return PartialView("_coordinatorAllRequestPartial", commonModels);
            }else if (DataOrCo == 3)
            {
                return PartialView("_merchandiserPartialRequest", commonModels);
            }
            else if(DataOrCo==2)
            {
                return PartialView("_dataEntryPartialViewRequest", commonModels);
            }
            else
            {
                return PartialView("_pendingRequestPartial", commonModels);
            }
        }
        public ActionResult GetTrackerUser(int Module)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");

Views/AdminUser/AdminUserView.cshtml
<style type="text/css">
    .btn,.form-control{
        border-radius:0px;
    }
</style>
<font size="2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul class="nav">
                    <li><a href="#" onclick="changeDiv(3)">Dashboard</a></li>
                    <li><a href="#" onclick="AllRequestById()">All Request</a></li>
                    <li><a href="#" onclick="GetAdminPending(0)">All Task</a></li>
                    <li><a href="#" onclick="GetAdminPending(1)">Pending To Co ordinator</a></li>
                    <li><a href="#" onclick="GetAdminPending(2)">Assign To D.E.O</a></li>
                    <li><a href="#" onclick="GetAdminPending(8)">Closed List </a></li>
                    <li><a href="#" onclick="changeDiv(5)">Report View</a></li>
                </ul>
            </div>
            <div class="col-md-10">
                <h3 style="text-align:center">Admin Dashboard</h3>
                <div id="admin_dashboard">

                </div>
            </div>
        </div>
    </div>
    <div class="modal" id="modalTaskPreview">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Request Number: <input id="RequestCoId" type="text" style="border:none;background:none" disabled /> </h4>
                </div>
                <div id="modaltaskbody" class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" id="remove_button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</font>
<script type="text/javascript">
    function AllRequestById() {
        var urlpath = '@Url.Action("AllMasterRequest", "AdminUser")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: {},
                    async: true,
                    success: function(data) {
                        if (data) {
                            $('#admin_dashboard').empty();
                            $('#admin_dashboard').html(data);
                            $("#requestTableList").DataTable();
                        }

                },
                error: function () {
                    swal({
                        title: 'Something Went Wrong!!',
                        type: 'error',
                        closeOnCancel: true
                    });
                }
            });
    }
    function AdminGetDetails(RequestId) {
        var urlpath = '@Url.Action("GetRequestAdmin", "AdminUser")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { RequestId: RequestId },
                    async: true,
                    success: function(data) {
                        $('#admin_dashboard').empty();
                        $('#admin_dashboard').html(data);
                    }
                });
    }
    function changeDiv(status) {
        var urlpath = '@Url.Action("ChangeDivView", "Tracker")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: {status:status},
                    async: true,
                    success: function(data) {
                        if (data) {
                            $('#admin_dashboard').empty();
                            $('#admin_dashboard').html(data);
                        }
                    }
            });
    }
    function colorChange(elem) {
        $(elem).css({ "border-color": "#d3d3d3" });
    }
    function GetInformationBYRequest(requestId,reqCod,oper,revi) {
        var urlpath = '@Url.Action("GetCoordinatorFilesDatabase", "AdminUser")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { RequestId: requestId, Reqcod: reqCod, OperationId:oper, Revision:revi,Partial:"_requestdetails_admin"},
                async: true,
                success: function (data) {
                        if (data) {
                            $('#modaltaskbody').empty();
                            $('#modaltaskbody').html(data);
                            $('#modalTaskPreview').show();
                            $('#RequestCoId').val(reqCod);
                            CommentsTable(reqCod);
                        }

                    }
                });
    }

    function InsertComments(requestId) {
        if ($("#commentsText").val().length < 1) {

        } else {
            var comments = $("#commentsText").val();
            var urlpath = '@Url.Action("InsertComments", "Tracker")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { RequestId: requestId, Comments: comments },
                    async: true,
                    success: function(data) {
                        if (data) {
                            $("#commentsText").val("");
                            CommentsTable(requestId);
                        }
                    }
                });
        }
        
    }
    function CommentsTable(requestId) {
            var urlpath = '@Url.Action("ReadAllComments", "Tracker")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { RequestId: requestId },
                    async: true,
                    success: function(data) {
                        if (data) {
                            $("#coordinatorComments").empty();
                            for (var i = 0; i < data.length; i++) {
                                        var newRow = $('<tr>');
                                        var cols = "";
                                        cols += '<td style="width:20%;color:blue">' + data[i].UserName + '</td>';
                                        cols += '<td style="width:30%;">' + data[i].CreateTime + '</td>';
                                        cols += '<td style="width:50%;word-break: break-word">' + data[i].ReviewMessage + '</td></tr>';
                                newRow.append(cols);
                                $("#coordinatorComments").append(newRow);
                            }
                            
                        }
                    }
                });    
    }


    function GetAdminPending(status) {
         var urlpath = '@Url.Action("GetAdminPending", "AdminUser")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: {Status:status},
                    async: true,
                    success: function(data) {
                        if (data) {
                            $('#admin_dashboard').empty();
                            $('#admin_dashboard').html(data);
                            $('#pendigcotablelist').dataTable(
                                {
                                    
                                    lengthMenu: [
                                        [10, 25, 50,-1],
                                        ['10', '25', '50', 'All']
                                    ],
                                    
                                    buttons: [
                                        'copy',
                                        'csv', 'excel', 'print'
                                    ],
                                }
                            );
                        }
                    }
            });
    }

    function AssignRequestToDataEntry(requestedId,assignto,updateSLA) {
        var urlpath = '@Url.Action("AssignRequestDataEntry", "Tracker")';
        $.ajax({
            url: urlpath,
            type: "Post",
            data: { RequestId: requestedId, AssignTo: assignto, UpdateSLA: updateSLA },
            async: true,
            success: function (data) {
                if (data) {
                    swal({
                        title: 'Request Number Successfully Assigned',
                        type: 'success',
                        closeOnCancel: true
                    }, function () {
                            GetAdminPending(1);
                            $('#modalTaskPreview').modal('hide');
                    });
                }
            }
        });
    }

    function GetDataEntryUser(module) {
        var urlpath = '@Url.Action("GetTrackerUser", "Tracker")';
                $.ajax({
                url: urlpath,
                type: "Post",
                data: { Module:module},
                async: true,
                success: function (data) {
                    if (data) {
                        $("#assignTo").empty();
                        for (var i = 0; i < data.length; i++) {
                            $("#assignTo").append($("<option></option>").val(data[i].UserInformationId)
                                    .html(data[i].UserInformationName));
                        }
                    }
                }
                });
    }

    function GetDataEntryReport() {
        var formDate = $("#formdateinput").val();
        var toDate = $("#todateInput").val();
        if (formDate == "") {
            $('#formdateinput').css({ "border-color": "#FF0000" });
        } else if (toDate=="") {
            $('#todateInput').css({ "border-color": "#FF0000" });
        } else {
            var urlpath = '@Url.Action("GetDataEntryReport", "AdminUser")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { FormDate: formDate, ToDate: toDate },
                    async: true,
                    success: function(data) {
                        if (data) {
                            $('#reportPartialView').empty();
                            $('#reportPartialView').html(data);
                            $('#reportTable').dataTable(
                                {     
                                      dom: 'Blfrtip',
                                      buttons: [
                                          'copy',
                                          'csv', 'excel', 'print'
                                    ],
                                      dom: 'Blfrtip',
                                      lengthMenu: [
                                          [-1,10, 25, 50],
                                          ['All Rows','10', '25', '50']
                                      ],
                                   
                                  
                                }
                            );
                        }
                    }
            });
        }

    }
</script>

Views/AdminUser/_ReportPartialView.cshtml
<div class="row">
    <h3 style="text-align:center">Data Entry Report </h3>
    <div class="col-md-4">
        <label>From Date</label>
        <input type="date" class="form-control" />
    </div>
    <div class="col-md-4">
        <label>To Date</label>
        <input type="date" class="form-control" />
    </div>
    <div class="col-md-4">
        <label>Action</label>
        <input type="button" class="form-control btn btn-sm btn-success" value="Genrate Report" />
    </div>
</div>

Views/AdminUser/_requestdetails_admin.cshtml
@model DataEntry_Tracker.Models.CommonModel

<table class="" width="100%" border="1">
    <tbody>
        <tr>
            <th>Operation Name</th>
            <td>@Model.BaseOperationName</td>
        </tr>
        <tr>
            <th>Instruction</th>
            <td>@Model.Instruction</td>
        </tr>
        <tr>
            <th>Create Time</th>
            <td>@Model.CreateDate.ToString("dd MMM yyyy h:mm:ss tt")</td>
        </tr>
        <tr>
            <th>Assign To</th>
            <td>@Model.UserName</td>
        </tr>
        <tr>
            <th>No of Operation</th>
            <td>@Model.NoOfTransections</td>
        </tr>
        <tr>
            <th>Estimated Time</th>
            <td>@Model.RequestTime min</td>
        </tr>
        <tr>
            <th>Assign Time</th>
            <td>
                @if (Model.CoUpdatedBy != "")
                {@DateTime.Parse(Model.CoUpdatedBy).ToString("dd MMM yyyy h:mm:ss tt")}
            </td>
        </tr>
        <tr>
            <th>Entry Started</th>
            <td>
                @if (Model.DataEntryCreated != "")
                {@DateTime.Parse(Model.DataEntryCreated).ToString("dd MMM yyyy h:mm:ss tt")}
            </td>
        </tr>
        <tr>
            <th>Entry End</th>
            <td>
                @if (Model.DataEntryUpdated != "")
                {@DateTime.Parse(Model.DataEntryUpdated).ToString("dd MMM yyyy h:mm:ss tt")}
            </td>
        </tr>
        <tr>
            <th>Progress</th>
            @if (Model.Progress == 2)
            {
                <td style="color:red">Pending</td>
            }
            else
            {
                <td style="color:green">Processing</td>
            }
        </tr>
    </tbody>
</table>


@if (Model.fileUploadModelsList != null)
{
    <table border="1" width="100%" style="text-align:center">
        <caption>Files & Instructions</caption>
        <tr>
            <th>
                No
            </th>
            <th>
                File Name
            </th>
            <th>
                Instructions
            </th>
            <th>
                Action
            </th>
        </tr>
        @{ int count = 1;}
        @foreach (var item in Model.fileUploadModelsList)
        {
            <tr>
                <td>
                    @count
                </td>
                <td>
                    @item.FileUploadName
                </td>
                <td>
                    @item.Instructions
                </td>
                <td>
                    @Html.ActionLink("Download", "DownloadFile", "Tracker", new { filepath = item.FileUploadPath.ToString(), filename = item.FileUploadName.ToString() }, new { @target = "_blank" })
                </td>
            </tr>
            count++;
        }

    </table>
}
<p>Comments Section</p>
<div id="comments_section" class="container" style="overflow-wrap:inherit; width:100%;overflow-y: scroll;height:100px;border:1px solid;margin-top:5px">
    <table width="100%" id="coordinatorComments">
    </table>

</div>
@if (Model.Progress != 8)
{
    <table style="text-align:center;width:80%;margin-left:10%;margin-top:2px">
        <tr>
            <td style="width:80%"><input type="text" style="width:100%" id="commentsText" /></td>
            <td style="width:20%"> <input type="button" style="padding:2px" value="Comments" class="btn btn-sm btn-success" onclick="InsertComments(@Model.RequestCodId)" /></td>
        </tr>
    </table>
}
<br />
@if (Model.Progress == 1 || Model.Progress == 9)
{
    <br />
    <table width="100%">
        <tr style="text-align:center">
            <td><label for="assignTo">Assign To:  </label></td>
            <td>
                <select id="assignTo" class="form-control" style="border-radius:0px;"></select>
            </td>
            <td>
                <input id="slaUpdate" value="@Model.RequestTime" style="border-radius:0px;margin-left:10px" />
            </td>
            <td>
                <button type="button" class="btn btn-info btn-sm" id="assignTodataentry">Assign </button>
            </td>
            <td>
                <button type="button" class="btn btn-danger btn-sm" id="rejectRequest" onclick="UpdateStartOrEnd(@Model.RequestCodId,7)">Return </button>
            </td>
            @*<td>
                    <button type="button" class="btn btn-success btn-sm" id="assignTodataentry" onclick="AssignRequestToDataEntry(@Model.RequestCodId,0)">Assign Own </button>
                </td>*@
        </tr>
    </table>
}
<script type="text/javascript">
    GetDataEntryUser(0);
    $("#assignTodataentry").click(function () {
        var assignname = $("#assignTo").val();
        var requestId = parseInt($("#RequestCoId").val());
        var updateSLA = $("#slaUpdate").val();
        if (!$.isNumeric($("#slaUpdate").val())) {
            $('#slaUpdate').css({ "border-color": "#FF0000" });
        }
        AssignRequestToDataEntry(requestId, assignname, updateSLA);
    });
</script>