Controllers/SupplyChainController.cs
using DataEntry_Tracker.DAL;
using DataEntry_Tracker.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DataEntry_Tracker.Controllers
{
    public class SupplyChainController : Controller
    {
        SupplyChainDAL supplyChain = new SupplyChainDAL();
        TrackerDAL trackerDAL = new TrackerDAL();
        // GET: SupplyChain
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SupplyChainCoordinator()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            return View();
        }

        public ActionResult SupplyUserView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            return View();
        }

        public ActionResult GetSupplyChainRequest(int Progress,int UserType)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            
            if (UserType == 1)
            {
                return PartialView("_supplyChainMenuMerchand", supplyChain.GetSupplyChainRequest(userID, Progress, UserType));
            }
            else if (UserType == 2)
            {
                return PartialView("_coordinatorPartial", supplyChain.GetSupplyChainRequest(userID, Progress, UserType));
            }
            else
            {
                return PartialView("_userPartialView", supplyChain.GetSupplyChainRequest(userID, Progress, UserType));
            }
        }
        public ActionResult GetDetailsSupplyChain(int SupRequestId,int UserType)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            if (UserType == 1)
            {
                return PartialView("_supplyChainDetailsMarchand", supplyChain.GetDetailsRequestSupply(userID, SupRequestId));
            }else if (UserType == 2)
            {
                return PartialView("_CoordinatorDetailsPartial", supplyChain.GetDetailsRequestSupply(userID, SupRequestId));
            }
            else
            {
                return PartialView("_userDetailsView", supplyChain.GetDetailsRequestSupply(userID, SupRequestId));
            }
           
        }

        public ActionResult AssigntoUsers(int SupplyChainId,int AssignTo)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            return Json(supplyChain.AssignToUsers(SupplyChainId,userID,AssignTo),JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SupplyChainUpdateTime(int SupplyChainID, int Progress)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            ResultResponse result = new ResultResponse();
            if (Progress == 3)
            {
                if (trackerDAL.CheckDataEntryEngagged(userid,2) == 0)
                {
                    return Json(supplyChain.SupplyChainUpdateTime(SupplyChainID, userid, Progress), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(supplyChain.SupplyChainUpdateTime(SupplyChainID, userid, Progress), JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult SavePoAginistRequest(RequestSupplyChain requestSupplyChain)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            return Json(supplyChain.SavePoToRequest(requestSupplyChain,userid), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult LOPoNameBYRequest(int RequestID)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<LoadPoCatagory> comolList =supplyChain.LoadPoByRequest(RequestID);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }

    }
}

Controllers/TrackerController.cs
using DataEntry_Tracker.DAL;
using DataEntry_Tracker.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataEntry_Tracker.Controllers
{
    public class TrackerController : Controller
    {

        TrackerDAL trackerDAL = new TrackerDAL();
        // GET: Tracker
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetUnitsFromDataBase()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetUnitsDatabase(userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetBuyerFromDataBase()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetBuyerFromDatabase(userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult LoadPoCatagory()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<LoadPoCatagory> comolList = trackerDAL.LoadPoFromDataBase(userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetAllBaseOperationsDatabase()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> baselist = trackerDAL.GetAllBasOperation(userid);
            return Json(baselist, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetSeasonFromDatabase(int buyerId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetSeasonFromDatabas(buyerId, userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetStylesFromFromDatabase(int seasonId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> comolList = trackerDAL.GetStylesFromDatabase(seasonId,userid);
            return Json(comolList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetFilesFromDatabase(int RequestId,int Status)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<FileUploadModel> comolList = trackerDAL.GetFilesByRivisionRequest(RequestId,Status);
            return PartialView("_showAllNewUploadFiles", comolList);
        }

        public ActionResult GetCoordinatorFilesDatabase(int RequestId, int Reqcod, int OperationId,int Revision,string Partial)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            CommonModel comolList = trackerDAL.DetailsInformationRequest(RequestId,OperationId,Revision,userid,Reqcod);
            return PartialView(Partial, comolList);
        }

        public ActionResult CoordinatorDetailsFirstime(int RequestId, int Reqcod, int OperationId, int Revision, string Partial,int Status)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            if (Status == 0)
            {
                bool res = trackerDAL.CordinatorTimeUpdate(Reqcod);
            }
            CommonModel comolList = trackerDAL.DetailsInformationRequest(RequestId, OperationId, Revision, userid, Reqcod);
            return PartialView(Partial, comolList);
        }

        public ActionResult CreateSupplyChain(int RequestId, int NumberTrans,string Partial)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);

            CommonModel comolList = new CommonModel();
            comolList.RequestCodId = RequestId;
            comolList.NoOfTransections = NumberTrans;
            return PartialView(Partial, comolList);
        }


        public ActionResult CreateMarchandiseRequest()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }
        public ActionResult MerchandiseCreateView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }
        public ActionResult DataEntryView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }

        public ActionResult CoordinatorView()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }
        [HttpPost]
        public ActionResult AllRequestById()
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            return PartialView("_allRequestPartialView",trackerDAL.GetAllRequestById(userid));
        }

        [HttpPost]
        public ActionResult DeleteFiles(int FileuploadId,int TableName)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            string filepath = trackerDAL.DeleteFile(FileuploadId,userID,TableName);
            bool result = false;
                    try
                    {
                        System.IO.File.Delete(filepath);
                        result = true;
                    }
                    catch (IOException ioExp)
                    {
                        Console.WriteLine(ioExp.Message);
                        result = false;
                    }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GenarateNewRequest(CommonModel commonModel)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            CommonModel returnmodel = trackerDAL.SaveRequestReturnPrimarykey(commonModel,userID);
            returnmodel.BuyerName = Server.HtmlDecode(commonModel.BuyerName);
            return PartialView("_merchandiseOperationCreation", returnmodel);
        }

        [HttpPost]
        public ActionResult GetRequestInformationById(int RequestId)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userID = Convert.ToInt32(Session["TrackerUserId"].ToString());
            CommonModel returnmodel = trackerDAL.GetRequestInformationByReId(RequestId);
            returnmodel.RevisionList = new List<CommonModel>();
            returnmodel.RevisionList = trackerDAL.GetMerchandRivisionProgress(RequestId);
            return PartialView("_merchandiseOperationCreation", returnmodel);
        }

        public ActionResult GetPendingRequest(int Pending,int DataOrCo)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            int userid = Convert.ToInt32(Session["TrackerUserId"]);
            List<CommonModel> commonModels = new List<CommonModel>();
            commonModels = trackerDAL.GetAllPendingRequest(Pending,userid,DataOrCo);
            if (DataOrCo == 1)
            {
                return PartialView("_coordinatorAllRequestPartial", commonModels);
            }else if (DataOrCo == 3)
            {
                return PartialView("_merchandiserPartialRequest", commonModels);
            }
            else if(DataOrCo==2)
            {
                return PartialView("_dataEntryPartialViewRequest", commonModels);
            }
            else
            {
                return PartialView("_pendingRequestPartial", commonModels);
            }
        }
        public ActionResult GetTrackerUser(int Module)
        {
            if (Session["TrackerUserId"] == null)
            {
                return RedirectToAction("Index", "Account");

Views/SupplyChain/SupplyChainCoordinator.cshtml
@{
    ViewBag.Title = "SupplyChainCoordinator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <style type="text/css">
        .active {
            background-color: #c4c4c4;
        }
        .sweet-alert{
            background-color:#C3C4C5;
        }
    </style>
    <font size="2" face="Calibri">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                    <ul class="nav">
                        <li><a href="#" onclick="ALLRequestBySupplyChain(1,2)" >Pending Request </a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(2,2)">Assigned Request</a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(3,2)">User In Progress</a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(4,2)">Return Form User</a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(5,2)">Return To Merchand</a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(6,2)">Complete Request</a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(7,2)">Pending For Payment</a></li>
                        <li><a href="#" onclick="ALLRequestBySupplyChain(8,2)">Payment COmplete</a></li>
                    </ul>
                </div>
                <div class="col-md-10">
                    <h3 style="text-align:center">Supply Chain <span id="spmenuid">Co ordinator </span></h3>
                    <div id="supplyDashboard"> </div>
                </div>
            </div>
        </div>
        <div class="modal" id="supplyModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close"
                                data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="modaltaskbody" class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="remove_button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </font>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $('li > a').click(function() {
        $('li').removeClass();
        $(this).parent().addClass('active');
        $("#spmenuid").html($(this).html());
    });

    function ALLRequestBySupplyChain(progress,userType) {
         var urlpath = '@Url.Action("GetSupplyChainRequest", "SupplyChain")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { Progress: progress,UserType: userType},
                    async: true,
                    success: function(data) {
                        if (data) {
                            $('#supplyDashboard').empty();
                            $('#supplyDashboard').html(data);
                            $('#coordinatorTable').DataTable({
                                "order": [[3, "desc"]],
                                "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ]
                            });
                        }
                },
                error: function (xhr, status, error) {
                    swal({
                        title: 'Something Went Wrong!!',
                        type: 'error',
                        closeOnCancel: true
                    });
                }
            });
    }
    function GetDetailsSupplyRequest(SupRequestId,userType) {
        var urlpath = '@Url.Action("GetDetailsSupplyChain", "SupplyChain")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { SupRequestId: SupRequestId, UserType: userType },
                async: true,
                success: function (data) {
                        if (data) {
                            $('#modaltaskbody').empty();
                            $('#modaltaskbody').html(data);
                            $('#supplyModal').show();
                            GetDataEntryUser(3);
                           // CommentsTable(reqCod);
                        }

                    }
                });
    }

    function GetDataEntryUser(module) {
        var urlpath = '@Url.Action("GetTrackerUser", "Tracker")';
                $.ajax({
                url: urlpath,
                type: "Post",
                data: { Module:module},
                async: true,
                success: function (data) {
                    if (data) {
                        $("#assignsupply").empty();
                        for (var i = 0; i < data.length; i++) {
                            $("#assignsupply").append($("<option></option>").val(data[i].UserInformationId)
                                    .html(data[i].UserInformationName));
                        }
                    }
                }
                });
    }
    function AssignToSupplyChain(supplyChainID,assignto) {
        var urlpath = '@Url.Action("AssigntoUsers", "SupplyChain")';
        $.ajax({
            url: urlpath,
            type: "Post",
            data: { SupplyChainId: supplyChainID, AssignTo: assignto },
            async: true,
            success: function (data) {
                if (data) {
                    $('#supplyModal').modal('hide');
                    ALLRequestBySupplyChain(2, 2);
                }
            }
        });
    }
    function CoordinatorAssign(reuestId) {
        swal({
            title: 'Are you sure?',
            text: "This Request Assign To Users",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes'
        }, function () {
            var assignname = $("#assignsupply").val();
                AssignToSupplyChain(reuestId, assignname);

        });
    }
    function UpdateOrClose(requestedId,progress) {
         var urlpath = '@Url.Action("SupplyChainUpdateTime", "SupplyChain")';
        $.ajax({
            url: urlpath,
            type: "Post",
            data: { SupplyChainID: requestedId , Progress:progress},
            async: true,
            success: function (data) {
                if (data) {
                    swal({
                        title: 'Done',
                        type: 'success',
                        closeOnCancel: true
                    }, function () {
                          ALLRequestBySupplyChain(1, 2);
                        $('#supplyModal').modal('hide');
                    });
                } else {
                    swal({
                        title: "Plase finish the Current Job First !!!!",
                        type: 'error',
                        closeOnCancel: true
                    });
                }
            }
        });
    }
</script>

Views/SupplyChain/SupplyUserView.cshtml
@{
    ViewBag.Title = "SupplyUserView";
}
<style type="text/css">
    .active {
        background-color: #c4c4c4;
    }

    .sweet-alert {
        background-color: #C3C4C5;
    }
</style>
<font size="2" face="Calibri">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul class="nav">
                    <li><a href="#" onclick="AllAssignedWork(2,3)">Pending Request </a></li>
                    <li><a href="#" onclick="AllAssignedWork(3,3)">Request In Progress</a></li>
                    <li><a href="#" onclick="AllAssignedWork(6,3)">Completed Request</a></li>
                    <li><a href="#" onclick="AllAssignedWork(7,3)">All Request So far</a></li>
                </ul>
            </div>
            <div class="col-md-10">
                <h3 style="text-align:center">Supply Chain <span id="spmenuid">User View </span></h3>
                <div id="userDashboard"> </div>
            </div>
        </div>
    </div>
    <div class="modal" id="supplyModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modaltaskbody" class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" id="remove_button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</font>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $('li > a').click(function() {
        $('li').removeClass();
        $(this).parent().addClass('active');
        $("#spmenuid").html($(this).html());
    });

    function AllAssignedWork(progress,userType) {
         var urlpath = '@Url.Action("GetSupplyChainRequest", "SupplyChain")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { Progress: progress,UserType: userType},
                    async: true,
                    success: function(data) {
                        if (data) {
                            $('#userDashboard').empty();
                            $('#userDashboard').html(data);
                            $('#coordinatorTable').DataTable({
                                "order": [[3, "desc"]],
                                "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ]
                            });
                        }
                },
                error: function (xhr, status, error) {
                    swal({
                        title: 'Something Went Wrong!!',
                        type: 'error',
                        closeOnCancel: true
                    });
                }
            });
    }
    function GetDetailsSupplyRequest(SupRequestId,userType) {
        var urlpath = '@Url.Action("GetDetailsSupplyChain", "SupplyChain")';
            $.ajax({
                url: urlpath,
                type: "Post",
                data: { SupRequestId: SupRequestId, UserType: userType },
                async: true,
                success: function (data) {
                        if (data) {
                            $('#modaltaskbody').empty();
                            $('#modaltaskbody').html(data);
                            $('#supplyModal').show();
                           // CommentsTable(reqCod);
                        }

                    }
                });
    }
    function UpdateOrCloase(requestedId,progress) {
         var urlpath = '@Url.Action("SupplyChainUpdateTime", "SupplyChain")';
        $.ajax({
            url: urlpath,
            type: "Post",
            data: { SupplyChainID: requestedId , Progress:progress},
            async: true,
            success: function (data) {
                if (data) {
                    swal({
                        title: 'Done',
                        type: 'success',
                        closeOnCancel: true
                    }, function () {
                        AllAssignedWork(2, 3);
                        $('#supplyModal').modal('hide');
                    });
                } else {
                    swal({
                        title: "Plase finish the Current Job First !!!!",
                        type: 'error',
                        closeOnCancel: true
                    });
                }
            }
        });
    }
</script>

Views/SupplyChain/_CoordinatorDetailsPartial.cshtml
@model DataEntry_Tracker.Models.RequestSupplyChain
<style type="text/css">
</style>
<div id="modal_task">
    <table class="" width="100%" border="1">
        <tbody>
            <tr>
                <th width="30%">S.Request ID </th>
                <td width="70%">@Model.SupplyChainId</td>
            </tr>
            <tr>
                <th>Po Number</th>
                <td>@Model.PoNumber</td>
            </tr>
            <tr>
                <th>Sub Catagory Name</th>
                <td>@Model.PoCatagoryName</td>
            </tr>
            <tr>
                <th>Remarks</th>
                <td>@Model.Remarks</td>
            </tr>
            <tr>
                <th>Co-ordinator Name</th>
                <td>@Model.CoordinatorName</td>
            </tr>
            <tr>
                <th>Supply Chain User Name</th>
                <td>@Model.SpUserName</td>
            </tr>
            <tr>
                <th>Create Date</th>
                <td>@DateTime.Parse(Model.CreateTime).ToString("dd MMM yyyy h:mm:ss tt")</td>
            </tr>
            <tr>
                <th>OTT Date</th>
                <td>@DateTime.Parse(Model.OttDate).ToString("dd MMM yyyy")</td>
            </tr>
            <tr>
                <th>Assign Time</th>
                <td>
                    @if (Model.AssignTime != "")
                    {@DateTime.Parse(Model.AssignTime).ToString("dd MMM yyyy h:mm:ss tt")}
                </td>
            </tr>
            <tr>
                <th>Entry Started</th>
                <td>
                    @if (Model.StartTime != "")
                    {@DateTime.Parse(Model.StartTime).ToString("dd MMM yyyy h:mm:ss tt")}
                </td>
            </tr>
            <tr>
                <th>Entry End</th>
                <td>
                    @if (Model.EndTime != "")
                    {@DateTime.Parse(Model.EndTime).ToString("dd MMM yyyy h:mm:ss tt")}
                </td>
            </tr>
        </tbody>
    </table>

    @if (Model.fileUploadModel != null)
    {
        <table border="1" width="100%" style="text-align:center" id="modalfilelist">
            <caption>Files & Instructions</caption>
            <tr>
                <th>
                    File Name
                </th>
                <th>
                    Action
                </th>
            </tr>
            @foreach (var item in Model.fileUploadModel)
            {
                <tr id="@item.FileUploadId">
                    <td>
                        @item.FileUploadName
                    </td>
                    <td>
                        @Html.ActionLink("Download", "DownloadFile", "Tracker", new { filepath = item.FileUploadPath.ToString(), filename = item.FileUploadName.ToString() }, new { @target = "_blank" })
                    </td>
                </tr>
            }
        </table>
    }

    @*<p>Comments Section</p>
        <div id="comments_section" class="container" style="overflow-wrap:inherit; width:100%;overflow-y: scroll;height:100px;border:1px solid;margin-top:5px">
            <table width="100%" id="commentsSection">
            </table>

        </div>*@
    <br />
    @if (Model.Progressid == 1 || Model.Progressid == 4)
    {

        <table width="100%">
            <tr style="text-align:center">
                <td><label for="assignsupply">Assign To:  </label></td>
                <td>
                    <select id="assignsupply" class="form-control" style="border-radius:0px;"></select>
                </td>
                <td>
                    <button type="button" class="btn btn-success btn-sm" onclick="CoordinatorAssign(@Model.SupplyChainId)">Assign </button>
                </td>
                <td>
                    <button type="button" class="btn btn-danger btn-sm" id="rejectRequest" onclick="UpdateOrClose(@Model.SupplyChainId,5)">Return </button>
                </td>
            </tr>
        </table>
    }
    else if (Model.Progressid == 6)
    {
        <div style="text-align:center">
            <button type="button" class="btn btn-primary btn-sm" onclick="UpdateOrClose(@Model.SupplyChainId,7)">Pending For Payment</button>
        </div>

    }
    else if (Model.Progressid == 7)
    {
        <div style="text-align:center">
            <button type="button" class="btn btn-success btn-sm"  onclick="UpdateOrClose(@Model.SupplyChainId,8)">Payment Completed</button>
        </div>

    }

</div>